CREATE TABLE RESERVATION(
  id VARCHAR(255) NOT NULL,
  store_id VARCHAR(255) NOT NULL,
  creation_date DATETIME,
  PRIMARY KEY (id)
);

CREATE TABLE RESERVATION_LINE(
  id VARCHAR(255) NOT NULL,
  reservation_id VARCHAR(255) NOT NULL REFERENCES RESERVATION(id),
  description VARCHAR(255),
  quantity INT(255) NOT NULL,
  PRIMARY KEY (id)
)

